### ISSUE TITLE
Question: how to add songs

### ISSUE THREAD

**Issue by monkeystink** [Leather128/LeathersFunkinEngine#16]
okay so i tried adding songs with the mods folder but then it crashed my game saying [lime.utils.Assets] ERROR: There is no TEXT asset with an ID of "assets/data/ui skins/default/tord.txt" even though i made one there

**Comment by Leather128** [comment]
question: did u make the tord.txt in the data folder in your mod? or was it _append/data ?

**Comment by Leather128** [comment]
because it has to be in the data folder to work

**Comment by monkeystink** [comment]
data folder

**Comment by Leather128** [comment]
and you made sure to have the file in that exact path? (data/ui skins/default)?

**Comment by monkeystink** [comment]
yea

**Comment by Leather128** [comment]
hmmm can u show me the folder structure of the mod? (like from the mod folder it self)

**Comment by Leather128** [comment]
because if it cant find the file, then it's probably something with the folders

**Comment by monkeystink** [comment]
alr

**Comment by monkeystink** [comment]
you mean show the data folder or the ui skins folder?

**Comment by Leather128** [comment]
just show whats inside the folder that's inside the mods folder

**Comment by monkeystink** [comment]
alright

**Comment by monkeystink** [comment]
[mods.zip](https://github.com/Leather128/LeatherEngine/files/7428911/mods.zip)

**Comment by monkeystink** [comment]
btw i gotta go sleep since im in another timezone probably can we solve this tommorow?

**Comment by Leather128** [comment]
yea, also just saying, there is no file in data/ui skins/default/ called tord.txt

**Comment by monkeystink** [comment]
ohhhhh so i had to do it in mod folder

**Comment by Leather128** [comment]
yea

**Comment by Leather128** [comment]
although, the problem is different than that

**Comment by monkeystink** [comment]
alr thanks for helping

**Comment by monkeystink** [comment]
oh

**Comment by monkeystink** [comment]
anyways i gotta go sleep like i said bye

**Comment by Leather128** [comment]
cuz the only reason it's giving the error is because of these 
![image](https://user-images.githubusercontent.com/81660872/139136759-b868623b-242c-43ca-a593-ae682e284159.png)
in the chart but ima make a fix so that it doesnt crash also aight bye

**Comment by Leather128** [comment]
anyways this bug should be fixed, also there is a wiki page for adding songs [(Link)](https://github.com/Leather128/LeatherEngine/wiki/Adding-a-Song) so u should be good now
